name: json_rpc_codegen_workspace

environment:
  sdk: ^3.13.0

workspace:
  - packages/json_rpc_codegen
  - packages/json_rpc_codegen_builder

dev_dependencies:
  dart_pre_commit: ^6.1.4
  dart_test_tools: ^7.3.0
