name: json_rpc_codegen
description: Annotations for the dart code generator that generates typed client and server code for the json_rpc_2 package.
version: 2.1.1
homepage: https://github.com/Skycoder42/json_rpc_codegen
repository: https://github.com/Skycoder42/json_rpc_codegen.git

environment:
  sdk: ^3.13.0
resolution: workspace

dependencies:
  json_rpc_2: ^4.1.0
  meta: ^1.19.0
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4

dev_dependencies:
  build_runner: ^2.16.0
  dart_pre_commit: ^6.1.4
  dart_test_tools: ^7.3.0
  mockito: ^5.8.1
  test: ^1.31.1

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - meta
      - stream_channel
