name: CI/CD for json_rpc_codegen_builder

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/json_rpc_codegen_builder/**"
      - ".github/workflows/json_rpc_codegen_builder_ci.yaml"
      - ".github/workflows/json_rpc_codegen_builder_cd.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/json_rpc_codegen_builder
      buildRunner: true
      buildRunnerArgs: --delete-conflicting-outputs
      removePubspecOverrides: false
      unitTestPaths: test/unit
      minCoverage: 0
      integrationTestPaths: test/integration
  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/json_rpc_codegen_builder
      tagPrefix: json_rpc_codegen_builder-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
