name: json_rpc_codegen_builder
description: A dart code generator that generates typed client and server code for the json_rpc_2 package.
version: 1.0.0
homepage: https://github.com/Skycoder42/json_rpc_codegen
repository: https://github.com/Skycoder42/json_rpc_codegen.git

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.7.0
  json_rpc_codegen: ^1.0.0
  meta: ^1.10.0
  source_gen: ^1.4.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.4.0
  source_gen_test: ^1.0.6
  test: ^1.21.0
